#!/usr/bin/env python3

places=['Berlin', 'New York', 'Tokyo', 'Brazil', 'Rome']
print("Here is the original list:")
print(places)
print("\nHere is the sorted list:")
print(sorted(places))
print("\nHere is the original list again:")
print(places)
print("\nHere is the sorted list in reverse order:")
print(sorted(places, reverse=True))
print("\nHere is the original list again:")
print(places)
print("\nHere is the original list after being reversed:")
places.reverse()
print(places)
print("\nHere is the original list after being reversed again:")
places.reverse()
print(places)
print("\nHere is the original list after being sorted:")
places.sort()
print(places)
print("\nHere is the original list after being sorted in reverse order:")
places.sort(reverse=True)
print(places)